sudo: required
services:
  - docker

before_install:
  - docker build -t gustavoarmelin/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run gustavoarmelin/multi-docker npm test -- --coverage

after_success:
  # build docker images
  - docker build -t gustavoarmelin/multi-client ./client
  - docker build -t gustavoarmelin/multi-nginx ./nginx
  - docker build -t gustavoarmelin/multi-server ./server
  - docker build -t gustavoarmelin/multi-worker ./worker

  # docker hub login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to docker hub
  - docker push gustavoarmelin/multi-client
  - docker push gustavoarmelin/multi-nginx
  - docker push gustavoarmelin/multi-server
  - docker push gustavoarmelin/multi-worker
